const mongoose = require('mongoose');
mongoose.Promise = require('bluebird');

const { dbURI } = require('../config/environment');
mongoose.connect(dbURI);

const User = require('../models/user');
const Info = require('../models/info');

User.collection.drop();
Info.collection.drop();

User
  .create([{
    username: 'arrianneoshea',
    password: 'password',
    passwordConfirmation: 'password'
  },{
    username: 'james',
    password: '2309',
    passwordConfirmation: '2309'
  }, {
    username: 'olivia',
    password: 'password',
    passwordConfirmation: 'password'
  }, {
    username: 'jack',
    password: 'password',
    passwordConfirmation: 'password'
  }, {
    username: 'bob',
    password: 'password',
    passwordConfirmation: 'password'
  }, {
    username: 'calvin',
    password: 'password',
    passwordConfirmation: 'password'
  }, {
    username: 'daniel',
    password: 'password',
    passwordConfirmation: 'password'
  }, {
    username: 'eric',
    password: 'password',
    passwordConfirmation: 'password'
  }, {
    username: 'fab',
    password: 'password',
    passwordConfirmation: 'password'
  }, {
    username: 'geri',
    password: 'password',
    passwordConfirmation: 'password'
  }])
  .then((users) => {
    console.log(`${users.length} users created!`);

    return Info.create([{
      number: 2,
      children: 'false',
      pets: 'true',
      image: '',
      otherInfo: 'Seen a couple of times this week.',
      lat: '51.514672',
      lng: '-0.049095',
      createdBy: users[0]
    }, {
      number: 1,
      children: 'false',
      pets: 'true',
      image: '',
      otherInfo: '',
      lat: '51.512909',
      lng: '-0.066948',
      createdBy: users[0]
    }, {
      number: 3,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.510772',
      lng: '-0.077934',
      createdBy: users[0]
    }, {
      number: 1,
      children: 'true',
      pets: 'false',
      image: '',
      otherInfo: 'Worried that there is a child but have never seen them before so hopefully it is just a one off.',
      lat: '51.510238',
      lng: '-0.074673',
      createdBy: users[0]
    }, {
      number: 1,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.509811',
      lng: '-0.068665',
      createdBy: users[0]
    }, {
      number: 3,
      children: 'false',
      pets: 'true',
      image: '',
      otherInfo: 'Often seen travelling up and down the road',
      lat: '51.512909',
      lng: '-0.06403',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'true',
      image: '',
      otherInfo: 'May have seen this pair before',
      lat: '51.512802',
      lng: '-0.061111',
      createdBy: users[0]
    }, {
      number: 1,
      children: 'false',
      pets: 'true',
      image: '',
      otherInfo: 'This woman seems to be in a bad way and carrying a cat',
      lat: '51.513336',
      lng: '-0.059052',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'true',
      image: '',
      otherInfo: '',
      lat: '51.514191',
      lng: '-0.056648',
      createdBy: users[0]
    }, {
      number: 1,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 1,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.518464',
      lng: '-0.097847',
      createdBy: users[1]
    }, {
      number: 2,
      children: 'false',
      pets: 'true',
      image: '',
      otherInfo: '',
      lat: '51.517503',
      lng: '-0.098362',
      createdBy: users[1]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.514298 ',
      lng: '-0.092182',
      createdBy: users[1]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.513871',
      lng: '-0.098362',
      createdBy: users[1]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }, {
      number: 2,
      children: 'false',
      pets: 'false',
      image: '',
      otherInfo: '',
      lat: '51.515473',
      lng: '-0.061283',
      createdBy: users[0]
    }]);
  })
  .then((info) => {
    console.log(`${info.length} info created!`);
  })
  .catch((err) => {
    console.log(err);
  })
  .finally(() => {
    mongoose.connection.close();
  });
